<?php


return [
    'banks' => [
        ['name' => 'Banesco Banco Universal','status'=> '1', 'registered_by' => 1],
        ['name' => 'Banco de Venezuela','status'=> '1', 'registered_by' => 1],
        ['name' => 'BBVA Provincial','status'=> '1', 'registered_by' => 1],
        ['name' => 'Banco Mercantil','status'=> '1', 'registered_by' => 1],
        ['name' => 'Banco Occidental de Descuento (B.O.D.)','status'=> '1', 'registered_by' => 1],
        ['name' => 'Bicentenario Banco Universal','status'=> '1', 'registered_by' => 1],
        ['name' => 'Banco Nacional de Credito (BNC)','status'=> '1', 'registered_by' => 1],
        ['name' => 'Banco del Tesoro','status'=> '1', 'registered_by' => 1],
        ['name' => 'BanCaribe','status'=> '1', 'registered_by' => 1],
        ['name' => 'Banco Exterior','status'=> '1', 'registered_by' => 1],
        ['name' => 'Banco Sofitasa','status'=> '1', 'registered_by' => 1]
    ],
    'brands' => [
        ['id' => 1, 'name' => 'Chevrolet'],
        ['id' => 2, 'name' => 'Daf'],
        ['id' => 3, 'name' => 'Ford'],
        ['id' => 4, 'name' => 'GMC'],
        ['id' => 5, 'name' => 'Isuzu'],
        ['id' => 6, 'name' => 'Iveco'],
        ['id' => 7, 'name' => 'Mack Trucks'],
        ['id' => 8, 'name' => 'Mercedes Benz'],
        ['id' => 9, 'name' => 'Nissan'],
        ['id' => 10, 'name' => 'Renault Trucks'],
        ['id' => 11, 'name' => 'Scania'],
        ['id' => 12, 'name' => 'Toyota'],
        //Sin modelos
        ['id' => 13, 'name' => 'Dongfeng'],
        ['id' => 14, 'name' => 'Hino'],
        ['id' => 15, 'name' => 'Hyundai'],
        ['id' => 16, 'name' => 'JAC'],
        ['id' => 17, 'name' => 'Mitsubishi'],
        ['id' => 18, 'name' => 'Volkswagen'],
    ],
    'models' => [
        ['name' => 'NPR', 'brand_id' => 1],
        ['name' => 'NHR', 'brand_id' => 1],
        ['name' => 'NKR', 'brand_id' => 1],
        ['name' => 'FVR', 'brand_id' => 1],
        ['name' => 'DAF 95', 'brand_id' => 2],
        ['name' => 'DAF SSC', 'brand_id' => 2],
        ['name' => 'DAF XF 95 Tropco', 'brand_id' => 2],
        ['name' => 'DAF XF 105', 'brand_id' => 2],
        ['name' => 'CARGO 800', 'brand_id' => 3],
        ['name' => 'CARGO 900', 'brand_id' => 3],
        ['name' => 'CARGO 1000', 'brand_id' => 3],
        ['name' => 'CARGO 1100', 'brand_id' => 3],
        ['name' => 'HM 9500', 'brand_id' => 4],
        ['name' => 'GMC W-series', 'brand_id' => 4],
        ['name' => 'JH 9500', 'brand_id' => 4],
        ['name' => 'Astro 95 ', 'brand_id' => 4],
        ['name' => 'EXZ', 'brand_id' => 5],
        ['name' => 'FSR', 'brand_id' => 5],
        ['name' => 'Trooper 960', 'brand_id' => 5],
        ['name' => 'Luv SPACECAB', 'brand_id' => 5],
        ['name' => 'Stralis', 'brand_id' => 6],
        ['name' => 'Eurostar', 'brand_id' => 6],
        ['name' => 'Powerstar', 'brand_id' => 6],
        ['name' => 'Daily', 'brand_id' => 6],
        ['name' => 'Eurocargo', 'brand_id' => 6],
        ['name' => 'Trakker', 'brand_id' => 6],
        ['name' => 'RD688', 'brand_id' => 7],
        ['name' => 'Granite', 'brand_id' => 7],
        ['name' => 'B95 Autobomba', 'brand_id' => 7],
        ['name' => 'Modelo con caja roquera', 'brand_id' => 7],
        ['name' => 'Econic', 'brand_id' => 8],
        ['name' => 'Actros', 'brand_id' => 8],
        ['name' => 'Unimog', 'brand_id' => 8],
        ['name' => 'Antos/antos', 'brand_id' => 8],
        ['name' => 'Atleon', 'brand_id' => 9],
        ['name' => 'Trade', 'brand_id' => 9],
        ['name' => 'Vanette', 'brand_id' => 9],
        ['name' => 'Cabtstar', 'brand_id' => 9],
        ['name' => 'NT400', 'brand_id' => 9],
        ['name' => 'NT500', 'brand_id' => 9],
        ['name' => 'Master', 'brand_id' => 10],
        ['name' => 'T', 'brand_id' => 10],
        ['name' => 'Premium', 'brand_id' => 10],
        ['name' => 'Midlum', 'brand_id' => 10],
        ['name' => 'R470', 'brand_id' => 11],
        ['name' => 'R500', 'brand_id' => 11],
        ['name' => 'LB141S', 'brand_id' => 11],
        ['name' => 'LS111', 'brand_id' => 11],
        ['name' => 'Hiace', 'brand_id' => 12],
        ['name' => 'Hilux', 'brand_id' => 12],
        ['name' => 'Probox', 'brand_id' => 12],
    ],
    'transports' => [
        ['id' => 1, 'name' => 'Baranda-Estacas'],
        ['id' => 2, 'name' => 'Furgon'],
        ['id' => 3, 'name' => 'Gandola (Low-Boy)'],
        ['id' => 4, 'name' => 'Gandola (Remolque)'],
        ['id' => 5, 'name' => 'Gandola (Semiremolque)'],
        ['id' => 6, 'name' => 'Jaula'],
        ['id' => 7, 'name' => 'Plataforma'],
        ['id' => 8, 'name' => 'Remolque'],
    ],
    'weights' => [
        ['id' => 1, 'weight' => '10', 'registered_by' => 3],
        ['id' => 2, 'weight' => '20', 'registered_by' => 3],
        ['id' => 3, 'weight' => '30', 'registered_by' => 3],
        ['id' => 4, 'weight' => '40', 'registered_by' => 3],
        ['id' => 5, 'weight' => '50', 'registered_by' => 3],
        ['id' => 6, 'weight' => '60', 'registered_by' => 3],
        ['id' => 7, 'weight' => '70', 'registered_by' => 3],
        ['id' => 8, 'weight' => '80', 'registered_by' => 3],
    ],
    'bulks' => [
        ['id' => 1, 'bulk' => '10', 'registered_by' => 3],
        ['id' => 2, 'bulk' => '20', 'registered_by' => 3],
        ['id' => 3, 'bulk' => '30', 'registered_by' => 3],
        ['id' => 4, 'bulk' => '40', 'registered_by' => 3],
        ['id' => 5, 'bulk' => '50', 'registered_by' => 3],
        ['id' => 6, 'bulk' => '60', 'registered_by' => 3],
        ['id' => 7, 'bulk' => '70', 'registered_by' => 3],
        ['id' => 8, 'bulk' => '80', 'registered_by' => 3],
    ],
];